GET http://localhost:3334/api/restaurant/listar
Authorization: Bearer 
Content-Type: application/json

###

POST http://localhost:3334/api/restaurant/cadastrar
Authorization: Bearer 
Content-Type: application/json

{
 "Endereco" : "Rua alameda dos anjos Doce1",
 "Especialidade" : "Doces",
 "Nmro_Funcionarios" : 2
}


###

PUT http://localhost:3334/api/restaurant/alterarNmroFuncionarios/
Authorization: Bearer 
Content-Type: application/json

{
    "funcionarios" : 10
}

###

DELETE http://localhost:3334/api/restaurant/deletar/
Content-Type: application/json


###